export const wallet_provider_api=process.env.EXPO_PUBLIC_WALLET_PROVIDER_API;
export const WALLET_PROVIDER_TOKEN=process.env.EXPO_PUBLIC_WALLET_PROVIDER_TOKEN;
export const SECRET_TOKEN=process.env.EXPO_PUBLIC_SECRET_TOKEN;